name: Hello World Manual Test

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run: echo "Hello"
      
      - name: Echo with timestamp
        run: |
          echo "Hello at $(date)"
          echo "Workflow triggered successfully!"
